/// Flutter icons LanguagesIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LanguagesIcon
///      fonts:
///       - asset: fonts/LanguagesIcon.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class LanguagesIcon {
  LanguagesIcon._();

  static const _kFontFam = 'LanguagesIcon';
  static const String? _kFontPkg = null;

  static const IconData vue_no_color = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vue_color = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData node_js = IconData(0xf3d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData python = IconData(0xf3e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vuejs = IconData(0xf41f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData php = IconData(0xf457, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
